#!/usr/bin/env bash

CONFIG_APP_NAME="$(basename $(pwd) | tr "[:upper:]" "[:lower:]")"
CONFIG_USR_NAME="$(whoami)"
CONFIG_PKG_NAME="${CONFIG_USR_NAME}/${CONFIG_APP_NAME}"

CONFIG_PLATFORM="$(uname)"

docker_run="docker run -e LC_ALL=C.UTF-8"
if [[ -d app ]]; then
	docker_run+=" -v $(pwd)/app:/app"
fi

case ${CONFIG_PLATFORM} in
	Darwin)
		CONFIG_IP=$(ifconfig en1 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
		docker_run+=" -e DISPLAY=${CONFIG_IP}:0"
		docker_run+=" -e PULSE_SERVER=tcp:${CONFIG_IP}"
		;;
	Linux)
		CONFIG_IP=$(ip route | grep wlan0 | sed 's,^.*src \([^ ]\+\) .*$,\1,' | tail -n 1)
		docker_run+=" -e DISPLAY=:0.0"
		docker_run+=" -e PULSE_SERVER=tcp:${CONFIG_IP}"
		docker_run+=" -v /tmp/.X11-unix:/tmp/.X11-unix"
		;;
esac

docker_build() {
	cat << EOF > 01proxy
Acquire::HTTP::Proxy "http://${CONFIG_IP}:3142";
Acquire::HTTPS::Proxy "false";
EOF
	cp ../zshrc.conf .

	docker build -t ${CONFIG_PKG_NAME} .

	rm -rf 01proxy zshrc.conf
}

# On MAC
# socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"

# PulseAudio /etc/pulse/default.pa
# load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;192.168.1.0/24 auth-anonymous=1
